### ISSUE TITLE
Practica3_Equipo

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-equipo-mana#1]
[Practica_3_Equipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-equipo-mana/files/10763586/Practica_3_Equipo.pdf)

**Comment by YaelStO** [comment]
Utilizando la rúbrica el equipo obtuvo el 100/100 en la actividad

**Comment by josealfredo79** [comment]
Excelente...bien hecho...revisado..
